server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    resolver 127.0.0.11 valid=30s;

    # Proxy API Gateway requests
    location /api/ {
        # Use variable to prevent Nginx from failing startup if host is down
        set $api_gateway_upstream http://api-gateway:8080;
        proxy_pass $api_gateway_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy Keycloak requests
    location /auth/ {
        # Use variable to prevent Nginx from failing startup if host is down
        set $keycloak_upstream http://keycloak:8080;
        proxy_pass $keycloak_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
