version: '3.8'

services:
  # --- INFRASTRUCTURE ---
  # --- INFRASTRUCTURE ---
  redis:
    image: redis:alpine
    container_name: redis-prod
    networks:
      - bid-network
    restart: unless-stopped

  # --- MICROSERVICES ---
  eureka-server:
    image: vyomkorat/bid-system-eureka-server:latest
    container_name: eureka-server-prod
    # JVM Optimization: Limit memory for Eureka
    environment:
      JAVA_OPTS: "-Xmx128m"
    ports:
      - "8761:8761"
    networks:
      - bid-network

  auth-service:
    image: vyomkorat/bid-system-auth-service:latest
    container_name: auth-service-prod
    environment:
      JAVA_OPTS: "-Xmx256m"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:-5432}/${RDS_AUTH_DB:-auth_db}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - eureka-server
    networks:
      - bid-network
    restart: always

  auction-service:
    image: vyomkorat/bid-system-auction-service:latest
    container_name: auction-service-prod
    environment:
      JAVA_OPTS: "-Xmx384m"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:-5432}/${RDS_AUCTION_DB:-auction_db}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      REDIS_HOST: redis
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - auction_uploads:/app/uploads/images
    depends_on:
      - redis
      - eureka-server
    networks:
      - bid-network
    restart: always

  notification-service:
    image: vyomkorat/bid-system-notification-service:latest
    container_name: notification-service-prod
    environment:
      JAVA_OPTS: "-Xmx128m"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - eureka-server
    networks:
      - bid-network

  api-gateway:
    image: vyomkorat/bid-system-api-gateway:latest
    container_name: api-gateway-prod
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx256m"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - eureka-server
    networks:
      - bid-network

  frontend:
    image: vyomkorat/bid-system-frontend:latest
    container_name: frontend-prod
    ports:
      - "80:80"
    networks:
      - bid-network

networks:
  bid-network:
    driver: bridge

volumes:
  auction_uploads:
